### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by flcouselo** [a-busman/Backlogger#50]
I don't know if it's a bug or as intended but the statistics are showing the games in my wish list as part of the total. I don't find it useful since as a backlog... I would like to see only statistics of the games I own and I can actually play right now.

**Comment by a-busman** [comment]
Probably a bug. Will address.

**Comment by flcouselo** [comment]
Great! If you need beta testers just let me know.

**Comment by a-busman** [comment]
Solved in 6ad618be894888401903bd603c0a2f7be361f39c
