### ISSUE TITLE
Import/Export not working

### ISSUE THREAD

**Issue by flcouselo** [a-busman/Backlogger#54]
I'm trying to export my data from an iPhone 6 but it isn't working. I tried to import an older backup to an iPhone X but nothing happens.

**Comment by a-busman** [comment]
I noticed this recently, but then when I reloaded the app, my backup was there on a new iPhone. In v2.0 I plan on implementing CoreData with CloudKit so there will be no importing and exporting required. If you have a db already, it will migrate it to CoreData.
